<a href="https://colab.research.google.com/github/Bharat-coder-pro/WebDev/blob/main/Python4DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Python Basics 


In [3]:
#variables and inputs
a=int(input("no. of students : "))
n=input("your name : ")
print("no. of students are present is ",a,"\nname of the boy is ",n)

no. of students : 6
your name : fj
no. of students are present is  6 
name of the boy is 


In [7]:
#arithmetic operators 
a=int(input("enter your first number : "))
b=int(input("enter your second number : "))
print("addition of ",a," and ",b," is : ",a+b)
print("subtraction of ",a," and ",b," is : ",a-b)
print("multiplication of ",a," and ",b," is : ",a*b)
print(a/b)     #division 
print(a%b)     #modulus(for finding remainder)
print(a**b)    #for finding exponentiation
#this how you can implement all kinds of arithmetical operators in python very 
#easily

enter your first number : 3
enter your second number : 2
addition of  3  and  2  is :  5
subtraction of  3  and  2  is :  1
multiplication of  3  and  2  is :  6
1.5
1
9


In [8]:
#logical operators in python
a=int(input("enter any number : "))
b=int(input("enter any number : "))

print(a<b and a!=b)      # will return ture if both condition on both ends of and is gonna be true
print(a>b or a<b)        # will return true if either condition is gonna be true
print(not(a==b))         # will return true if the condition is false and if condition is true it will return false

enter any number : 4
enter any number : 9
True
True
False


# Numpy Package or Library in Python

### creating NumPy arrays 1D and 2D

In [7]:
import numpy as np
arr2D=[1,2,3,4,5,6,7],[8,9,10,11,12,13,14],[15,16,17,18,19,20,21,]
array2D=np.array(arr2D)
print(array2D)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]


In [9]:
import numpy as np
arr1d=[1,2,3,4,5],['a','b','a','c','a']      #homogenity of numpy arrays
arr1D=np.array(arr1d)
print(arr1D)

[['1' '2' '3' '4' '5']
 ['a' 'b' 'a' 'c' 'a']]


In [14]:
# creating identity matrix
import numpy as np
id_arr=np.eye(2,5)
print(id_arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


In [79]:
# creating array of random integers in a specific range
import numpy as np
rand=np.random.randint(1,101,100)
print(rand)


[ 34  14  16  42  23  25  22  50  27  90  68  32  89  49   4  13  47  91
  51  81  45  41  42  15  72  78  97  67  34  93  34  74  82  99  56  59
  83  22  69  23  25  71  37  53  90  86  35   1  44  33  36   9  66  34
  19  69  67  90  31  43  15  58  76  25  19  47  19  32  58  72  34  19
  98  61  11  73  12  78  18  67   9  70  62  15  34  59  57  11   5  45
  47 100  10  50  45  30  89  74  68  65]


In [20]:
#printing the last element of the array
print("last element of array : ",rand[-1])
#reversing the array
print("reversed array :- \n",rand[::-1])

last element of array :  26
reversed array :- 
 [ 26  82  40  93   5  42  45  15  29  59  49  46  55  21  95  92  35  22
  72  99  53  22  68  22  83  33  11  23  32  66  42  71  47 100  12  95
  73  81  14  20  49  57  96   3  87  12  23  13  77 100  90   2  55  89
  30  87  78  93  41  66  83  57  42  41  56  58  11  87  64  72  20  92
  17  70  24  87  61  35  20  68  60  54  27  71  10  85  17  12  58  45
  33  30  22  31  16  60   5  22  39]


In [28]:
#printing the specific element of the multiDarray
print("element at 2nd row and 5th column :",arr2D[2][5])

element at 2nd row and 5th column : 20


### Insertion in NumPy Arrays 

In [30]:
num=np.random.randint(1,51,50).reshape(10,5)        #inserting random integers using randint() function of NumPy
print(num)

[[21  3 26 16  8]
 [12 22 30 15 30]
 [20 18 25 25  4]
 [32  5 48 41 42]
 [23 39 26 22 28]
 [17  7 15  8  8]
 [27 45 30 19  1]
 [35 35 25 23 10]
 [42 32 22 20 30]
 [ 6 36  2 36 33]]


In [31]:
num1=np.arange(1,11).reshape(5,2)                   #using arange()function choosing a specific range and then by reshape() setting up the dimensions of the array
print(num1)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


### replacing elements

In [34]:
counts=np.arange(1,11)
counts[counts%2==0]=00             # using even odd logic simply done
print(counts)

[1 0 3 0 5 0 7 0 9 0]


### Conversion 1D to 2D array

In [42]:
numbers=[1,2,3,4,5,6,7,8,9,10]
numbers2D=np.array(numbers)
numbers2D.reshape(2,-2)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

### printing unique and common elements from an NumPy Array

In [45]:
common=np.intersect1d(rand,numbers)               #found common elements in arrays i.e. rand and numbers
print(common)

[4 5 6 7 8 9]


In [48]:
#choosing a specific range
print(counts[(counts >= 2 ) & (counts <= 8) ])              

[3 5 7]


# Pandas in Python

### creating series using dictionaries in Pandas in Python


In [51]:
import pandas as pd
dict1={"I":1,"Love":2,"You":3}
serie1=pd.Series(dict1)
print(serie1)

I       1
Love    2
You     3
dtype: int64


### Assigning Names to Indexing of Series
 

In [64]:
serie1.name="emotion"
print(serie1)



I       1
Love    2
You     3
Name: emotion, dtype: int64


In [68]:
dict2={"I":1,"Hate":2,"You":3}
serie2=pd.Series(dict2)
serie2.name='Emotion'
print(serie2)

I       1
Hate    2
You     3
Name: Emotion, dtype: int64


### Extracting elements that are not present in another series


In [71]:
unique=(~serie1.isin(serie2))                     #extract those elements which are not in serie1 but are present in serie2
print(unique)

I       False
Love    False
You     False
Name: emotion, dtype: bool


# Converting Pandas Series into a Pandas DataFrame

In [80]:
dataFrame1=pd.DataFrame(rand.reshape(10,10))
print(dataFrame1)                                                  # pandas dataframes don't show output with brackets likewise in NumPyArrays

    0    1   2   3   4   5   6   7   8   9
0  34   14  16  42  23  25  22  50  27  90
1  68   32  89  49   4  13  47  91  51  81
2  45   41  42  15  72  78  97  67  34  93
3  34   74  82  99  56  59  83  22  69  23
4  25   71  37  53  90  86  35   1  44  33
5  36    9  66  34  19  69  67  90  31  43
6  15   58  76  25  19  47  19  32  58  72
7  34   19  98  61  11  73  12  78  18  67
8   9   70  62  15  34  59  57  11   5  45
9  47  100  10  50  45  30  89  74  68  65
